package soa.model;
// Generated Mar 25, 2024, 1:32:21 AM by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Package generated by hbm2java
 */
public class MyPackage implements java.io.Serializable {

	private Integer id;
	private String name;
	private int price;
	private int wash;
	private int dry;
	@JsonIgnore
	private Set orderses = new HashSet(0);

	public MyPackage() {
	}

	public MyPackage(String name, int price, int wash, int dry, Set orderses) {
		this.name = name;
		this.price = price;
		this.wash = wash;
		this.dry = dry;
		this.orderses = orderses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public int getWash() {
		return this.wash;
	}

	public void setWash(int wash) {
		this.wash = wash;
	}

	public int getDry() {
		return this.dry;
	}

	public void setDry(int dry) {
		this.dry = dry;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

}
