package soa.model;
// Generated Mar 24, 2024, 4:22:54 PM by Hibernate Tools 6.3.1.Final

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private Integer id;
	private Employees employeesByCheckerId;
	private Employees employeesBySenderId;
	private Employees employeesByRecieverId;
	private Users users;
	private FabricSoftener fabricSoftener;
	private int packageId;
	private int temperatureId;
	private int plusdry;
	private String status;
	private WaterTemperature waterTemperature;
	private Package package_;

	public Orders() {
	}

	public Orders(Employees employeesByCheckerId, Employees employeesBySenderId, Employees employeesByRecieverId,
			Users users, FabricSoftener fabricSoftener, int packageId, int temperatureId, int plusdry, String status,
			WaterTemperature waterTemperature, Package package_) {
		this.employeesByCheckerId = employeesByCheckerId;
		this.employeesBySenderId = employeesBySenderId;
		this.employeesByRecieverId = employeesByRecieverId;
		this.users = users;
		this.fabricSoftener = fabricSoftener;
		this.packageId = packageId;
		this.temperatureId = temperatureId;
		this.plusdry = plusdry;
		this.status = status;
		this.waterTemperature = waterTemperature;
		this.package_ = package_;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Employees getEmployeesByCheckerId() {
		return this.employeesByCheckerId;
	}

	public void setEmployeesByCheckerId(Employees employeesByCheckerId) {
		this.employeesByCheckerId = employeesByCheckerId;
	}

	public Employees getEmployeesBySenderId() {
		return this.employeesBySenderId;
	}

	public void setEmployeesBySenderId(Employees employeesBySenderId) {
		this.employeesBySenderId = employeesBySenderId;
	}

	public Employees getEmployeesByRecieverId() {
		return this.employeesByRecieverId;
	}

	public void setEmployeesByRecieverId(Employees employeesByRecieverId) {
		this.employeesByRecieverId = employeesByRecieverId;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public FabricSoftener getFabricSoftener() {
		return this.fabricSoftener;
	}

	public void setFabricSoftener(FabricSoftener fabricSoftener) {
		this.fabricSoftener = fabricSoftener;
	}

	public int getPackageId() {
		return this.packageId;
	}

	public void setPackageId(int packageId) {
		this.packageId = packageId;
	}

	public int getTemperatureId() {
		return this.temperatureId;
	}

	public void setTemperatureId(int temperatureId) {
		this.temperatureId = temperatureId;
	}

	public int getPlusdry() {
		return this.plusdry;
	}

	public void setPlusdry(int plusdry) {
		this.plusdry = plusdry;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public WaterTemperature getWaterTemperature() {
		return this.waterTemperature;
	}

	public void setWaterTemperature(WaterTemperature waterTemperature) {
		this.waterTemperature = waterTemperature;
	}

	public Package getPackage() {
		return this.package_;
	}

	public void setPackage(Package package_) {
		this.package_ = package_;
	}

}
