package soa.model;
// Generated Mar 25, 2024, 1:32:21 AM by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer id;
	private String username;
	private String pass;
	private String name;
	private String tel;
	private String address;
	private int extra;
	private Set orderses = new HashSet(0);

	public Users() {
	}

	public Users(String username, String pass, String name, String tel, String address, int extra, Set orderses) {
		this.username = username;
		this.pass = pass;
		this.name = name;
		this.tel = tel;
		this.address = address;
		this.extra = extra;
		this.orderses = orderses;
	}
	public Users(String username, String pass, String name, String tel, String address, int extra) {
		super();
		this.username = username;
		this.pass = pass;
		this.name = name;
		this.tel = tel;
		this.address = address;
		this.extra = extra;
	}
	//Create

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public int getExtra() {
		return this.extra;
	}

	public void setExtra(int extra) {
		this.extra = extra;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

}
